create table users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) not null,
    password varchar(255) not null,
    name varchar(255) not null,
    email varchar(255) not null,
    enabled boolean not null,
    last_password_reset_date timestamp
);

CREATE UNIQUE INDEX username ON users(username);
CREATE UNIQUE INDEX email ON users(email);

create table roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) not null
);

CREATE UNIQUE INDEX name ON roles(name);

create table user_role (
    user_id bigint REFERENCES users(id),
    role_id bigint REFERENCES roles(id)
);